version: '1.0'

services:
  web:
    build: ./
    image: plannerfit-django-backend
    command: >
      sh -c "export DJANGO_SETTINGS_MODULE=plannerfit.settings.production &&
             python manage.py makemigrations &&
             python manage.py migrate --noinput &&
             gunicorn plannerfit.wsgi:application --bind 0.0.0.0:8000"

    volumes:
      - ./plannerfit/:/usr/src/plannerfit/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PlannerFit2023
      - POSTGRES_DB=plannerfit
  
volumes:
  postgres_data: